import {Recipe} from '../../types/ShoppingList.ts';

export const recipes: Recipe[] = [
  {
    id: '0',
    ingredients: [
      {id: '1', name: 'Flour', amount: '1½ c'},
      {id: '2', name: 'Baking powder', amount: '3½ tsp'},
      {id: '3', name: 'White sugar', amount: '1 tbsp'},
      {id: '4', name: 'Salt', amount: '¼ tsp'},
      {id: '5', name: 'Milk', amount: '1¼ c'},
      {id: '6', name: 'Butter, melted', amount: '3 tbsp'},
      {id: '7', name: 'Egg', amount: '1'},
    ],
    name: 'Pancakes',
    price: 20,
    rating: 4.5,
    ratingsAmount: 200,
    servingSize: '1 serving',
    source:
      'https://www.allrecipes.com/recipe/21014/good-old-fashioned-pancakes/',
    uri: 'https://www.allrecipes.com/thmb/VtvwUlahyCsWlcqWui0_9j13hWw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc()/21014-Good-old-Fashioned-Pancakes-mfs_002-0e249c95678f446291ebc9408ae64c05.jpg',
  },
  {
    id: '1',
    ingredients: [
      {id: '8', name: 'Milk', amount: '2 c'},
      {id: '9', name: 'Oats', amount: '⅓ c'},
      {id: '10', name: 'Weigh protein powder', amount: '3 tbsp'},
      {id: '11', name: 'Banana, frozen', amount: '1'},
      {id: '12', name: 'Peanutbutter', amount: '2 tbsp'},
    ],
    name: 'Protein Shake',
    price: 20,
    rating: 4.0,
    ratingsAmount: 150,
    servingSize: '1 serving',
    source:
      'https://www.everydayeasyeats.com/peanut-butter-banana-protein-shake/#recipe',
    uri: 'https://www.everydayeasyeats.com/wp-content/uploads/2017/07/Peanut-Butter-Banana-Protein-Shake-1-320x320.jpg',
  },
  {
    id: '2',
    name: 'Turkey Dish',
    rating: 4.0,
    ratingsAmount: 150,
    source: 'https://www.food.com/recipe/pulled-pork-crock-pot-131018',
    ingredients: [
      {id: '13', name: '97% Lean ground turkey', amount: '4½ oz'},
      {id: '14', name: 'Sweet potatoes', amount: '9 oz'},
      {id: '15', name: 'Extra virgin olive oil', amount: '1 tbsp'},
      {id: '16', name: 'Green Beans', amount: '1 c'},
      {id: '15', name: 'Salt', amount: '½ tsp'},
      {id: '16', name: 'Pepper', amount: '½ tsp'},
    ],
    servingSize: '1 serving',
    price: 20,
  },
];

export const recipes2: Recipe[] = [
  {
    id: '0',
    name: 'Spaghetti and Meatballs',
    rating: 4.3,
    ratingsAmount: 835,
    source:
      'https://www.allrecipes.com/recipe/85635/jenns-out-of-this-world-spaghetti-and-meatballs/',
    ingredients: [
      {id: '0', name: 'olive oil', amount: 3, metric: 'Tbsp'},
      {id: '1', name: 'chopped onion', amount: 0.75, metric: 'C'},
      {id: '2', name: 'garlic, minced', amount: 4, metric: 'cloves'},
      {id: '3', name: 'crushed tomatoes', amount: 32, metric: 'oz'},
      {id: '4', name: 'tomato paste', amount: 18, metric: 'oz'},
      {id: '5', name: 'water', amount: 1, metric: 'C'},
      {id: '6', name: 'sugar', amount: 0.5, metric: 'C'},
      {
        id: '7',
        name: 'chopped fresh oregano, divided',
        amount: 0.25,
        metric: 'cup',
      },
      {id: '8', name: 'dried bay leaf', amount: 1, metric: ''},
      {id: '9', name: 'salt and pepper', amount: null, metric: 'to taste'},
      {id: '10', name: 'ground round', amount: 1, metric: 'lb'},
      {
        id: '11',
        name: 'Italian seasoned bread crumbs',
        amount: 0.5,
        metric: 'C',
      },
      {id: '12', name: 'chopped fresh parsley', amount: 0.25, metric: 'C'},
      {id: '13', name: 'eggs, lightly beaten', amount: 2, metric: ''},
      {id: '14', name: 'grated Parmesan cheese', amount: 0.5, metric: 'C'},
      {id: '15', name: 'uncooked spaghetti', amount: 16, metric: 'oz'},
    ],
    servingSize: 8,
    uri: 'https://www.allrecipes.com/thmb/ZRn_kRepFg4kkyVDlW-xsA8af1k=/750x0/filters:no_upscale():max_bytes(150000):strip_icc()/754675-d5429c1bc87b4dc2a75d1f8e6c73221f.jpg',
    price: 20,
  },
  {
    id: '1',
    name: 'Protein Shake',
    rating: 4.0,
    ratingsAmount: 150,
    source: 'https://www.food.com/recipe/pulled-pork-crock-pot-131018',
    ingredients: [
      {id: '8', name: 'Milk', amount: '2 c'},
      {id: '9', name: 'Oats', amount: '⅓ c'},
      {id: '10', name: 'Weigh protein powder', amount: '3 tbsp'},
      {id: '11', name: 'Banana, frozen', amount: '1'},
      {id: '12', name: 'Peanutbutter', amount: '2 tbsp'},
    ],
    servingSize: '1 serving',
    price: 20,
  },
  {
    id: '2',
    name: 'Turkey Dish',
    rating: 4.0,
    ratingsAmount: 150,
    source: 'https://www.food.com/recipe/pulled-pork-crock-pot-131018',
    ingredients: [
      {id: '13', name: '97% Lean ground turkey', amount: '4½ oz'},
      {id: '14', name: 'Sweet potatoes', amount: '9 oz'},
      {id: '15', name: 'Extra virgin olive oil', amount: '1 tbsp'},
      {id: '16', name: 'Green Beans', amount: '1 c'},
      {id: '15', name: 'Salt', amount: '½ tsp'},
      {id: '16', name: 'Pepper', amount: '½ tsp'},
    ],
    servingSize: '1 serving',
    price: 20,
  },
];
